#!/bin/bash

# this script generates a table that illustrates in which cities carriers hand off, eg
#       Toronto | Chicago | Washington
# 7018     Y         Y          Y
# 852      Y         N          N
# 1257     N         N          N

echo "NOTE: this script uses a static declared table (the csvs for which can be generated by asn-handoffs.sh)"
# delete from asn_handoffs
# \copy asn_handoffs FROM '/home/ixmaps/scripts/asn_handoffs_dcan_nouoft_nodup_RENAME ME.csv' DELIMITER '|' CSV HEADER
# see further instructions as the end of this script

# add an input request here
declare TABLE="dcan"

echo ""
echo "Deleting old data..."
psql ixmaps -c "delete from asn_handoffs;"
echo "Copying in new data..."
psql ixmaps -c "\copy asn_handoffs FROM '/home/ixmaps/scripts/asn_handoffs_$TABLE.csv' DELIMITER '|' CSV HEADER"

declare -a cities=(
    'Toronto'
    'Ottawa'
    'Montreal'
    'Vancouver'
    'Victoria'
    'Winnipeg'
    'Calgary'
    'Halifax'
    'Quebec'
    'Edmonton'
    'Chicago'
    'New York'
    'Seattle'
    'Ashburn'
    'Washington'
    'Denver'
    'San Jose'
    'Kansas City'
    'Atlanta'
    'Los Angeles'
    'Buffalo'
    'Salt Lake City'
    'Boston'
    'Dallas'
    'San Francisco'
    'San Diego'
    'Miami'
    'Phoenix'
    'Nashville'
    'Portland'
    'St Louis'
    'Houston'
)

declare -a asns=(
    'asn_from = 6461 or asn_from = 17025'
    'asn_from = 33139'
    'asn_from = 17899'
    'asn_from = 7018 or asn_from = 5730 or asn_from = 4466'
    'asn_from = 577 or asn_from = 6549 or asn_from = 11489'
    'asn_from = 855'
    'asn_from = 0'
    'asn_from = 11727'
    'asn_from = 11290'
    'asn_from = 174 or asn_from = 2149'
    'asn_from = 7922 or asn_from = 33491 or asn_from = 33659'
    'asn_from = 15128'
    'asn_from = 11814 or asn_from = 14595'
    'asn_from = 11260'
    'asn_from = 0'
    'asn_from = 8282'
    'asn_from = 0'
    'asn_from = 6939'
    'asn_from = 0'
    'asn_from = 3356 or asn_from = 3549 or asn_from = 30686'
    'asn_from = 22822 or asn_from = 45396 or asn_from = 38622'
    'asn_from = 36676'
    'asn_from = 7122'
    'asn_from = 22573 or asn_from = 6058'
    'asn_from = 40029'
    'asn_from = 13768'
    'asn_from = 9443 or asn_from = 6407'
    'asn_from = 812 or asn_from = 3602'
    'asn_from = 803'
    'asn_from = 3561 or asn_from = 6347 or asn_from = 4298'
    'asn_from = 6327'
    'asn_from = 1239 or asn_from = 1803 or asn_from = 3644'
    'asn_from = 13319'
    'asn_from = 6453 or asn_from = 6421'
    'asn_from = 5645 or asn_from = 20375'
    'asn_from = 35911'
    'asn_from = 1299'
    'asn_from = 852 or asn_from = 7861 or asn_from = 54719'
    'asn_from = 701 or asn_from = 702 or asn_from = 703'
    'asn_from = 5769'
    'asn_from = 0'
    'asn_from = 30261'
    'asn_from = 20365 or asn_from = 36273'
    'asn_from = 22995'
)

declare -a carriers=(
    'AboveNet'
    'Acanac'
    'ACN Canada'
    'AT&T'
    'Bell'
    'Bell Aliant'
    'Bragg Communications'
    'Bruce Telecom'
    'Cogeco'
    'Cogent'
    'Comcast'
    'Comwave'
    'Distributel'
    'Eastlink'
    'Execulink'
    'Fido'
    'Fongo'
    'Hurricane Electric'
    'Koodo Mobile'
    'Level 3'
    'Limelight'
    'Mobilicity'
    'MTS allstream'
    'Northwestel'
    'Novus'
    'Peer 1'
    'Primus Canada'
    'Rogers'
    'Sasktel'
    'Savvis'
    'Shaw'
    'Sprint'
    'Storm Internet Service'
    'Tata'
    'Teksavvy'
    'Telebec'
    'TeliaNet/Telia Sonera'
    'Telus'
    'Verizon'
    'Videotron'
    'VIF Internet'
    'Virgin Mobile'
    'Wind Mobile'
    'Xplornet'
)

# generate 3 asn-handoff tables with DCan-noUoT-noDup, DCan-Bo-noUoT-noDups, DCan-noBo-noUoT-noDup
# then, for each

# write the header
TODAY=$(date +"%d-%m-%Y")

declare headerStr="HANDS OFF AT,"
for c in "${cities[@]}"
do
    headerStr+=$c
    headerStr+=","
done
echo $headerStr >> asn_handoffs_city_$TABLE_$TODAY.csv

declare -i i=0
for asn in "${asns[@]}"
do
    echo "Generating "${carriers[i]}"..."
    psql ixmaps -c "select asn_from, mm_city_from into asn_temp from asn_handoffs where $asn;"
    declare outputStr=""
    for city in "${cities[@]}"
    do
        tempStr=($(psql -d ixmaps -Atc "select exists(select 1 from asn_temp where mm_city_from = '$city');"))
        #echo $tempStr
        outputStr+=$tempStr
        outputStr+=","
    done
    psql ixmaps -c "drop table asn_temp;"
    echo ${carriers[i]}","$outputStr >> asn_handoffs_city_$TABLE_$TODAY.csv
    ((i++))
done


# if you need to set up the table again, make sure to set most defaults to null, this can help (but probably better to do it while creating the table)
# ixmaps=> SELECT 'ALTER TABLE '||table_name||' ALTER COLUMN '||column_name||' SET DEFAULT NULL;'
# ixmaps-> FROM information_schema.columns
# ixmaps-> WHERE table_name = 'asn_handoffs';

# create table asn_handoffs (
# tr_id_from integer,
# hop_from smallint,
# ip_addr_from inet,
# hostname_from character varying(80),
# asn_from integer,
# mm_lat_from double precision ,
# mm_lng_from double precision,
# lat_from double precision,
# lng_from double precision,
# mm_city_from character varying(60),
# mm_region_from character(2),
# mm_country_from character(2),
# mm_postal_from character varying(11),
# gl_override_from integer,
# short_name_from character varying(240),
# name_from character varying(240),
# dest_from character varying(80),
# dest_ip_from inet,
# sub_time_from timestamp with time zone,
# submitter_from character varying(80),
# zip_code_from character varying(10),
# hop_lh_from integer,
# ip_addr_lh_from inet,
# latency_from integer,
# tr_id_to integer,
# hop_to smallint,
# ip_addr_to inet,
# hostname_to character varying(80),
# asn_to integer,
# mm_lat_to double precision,
# mm_lng_to double precision,
# lat_to double precision,
# lng_to double precision,
# mm_city_to character varying(60),
# mm_region_to character(2),
# mm_country_to character(2),
# mm_postal_to character varying(11),
# gl_override_to integer,
# short_name_to character varying(240),
# name_to character varying(240),
# dest_to character varying(80),
# dest_ip_to inet,
# sub_time_to timestamp with time zone,
# submitter_to character varying(80),
# zip_code_to character varying(10),
# hop_lh_to integer,
# ip_addr_lh_to inet,
# latency_to integer
# );
